[General]
checkForUpdates=true
contrastOpacity=188
copyAndCloseAfterUpload=true
copyPathAfterSave=true
drawColor=#ff0000
drawThickness=3
filenamePattern=Screenshot from %F %T
historyConfirmationToDelete=true
ignoreUpdateToVersion=14.0.0
predefinedColorPaletteLarge=true
saveAfterCopy=true
saveAsFileExtension=png
saveLastRegion=true
savePath=/home/murilo-elias/Pictures/Screenshots
savePathFixed=true
showDesktopNotification=true
showStartupLaunchMessage=false
startupLaunch=true
uiColor=#007974
undoLimit=100
uploadHistoryMax=20
userColors=picker, #800000, #ff0000, #ffff00, #00ff01, #008000, #00ffff, #0000ff, #ff00ff, #800080
